name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:

permissions:
  contents: read

jobs:
  test-and-package:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Test and package in Dev Container
        if: ${{ !env.ACT }}
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          push: never
          runCmd: |
            actionlint
            npm test
            npm run syntaxcheck
            npm run package:extension

      - name: Test and package in act runner
        if: ${{ env.ACT }}
        run: |
          npm test
          npm run syntaxcheck
          npm run package:extension

      - name: Upload packaged extension
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: poe2-my-watch-${{ github.sha }}
          path: dist/*.zip
          if-no-files-found: error
          retention-days: 14
